version: '3.8'

services:
  # 1. SERVICIO DE APLICACIÓN WEB (Apache + PHP 8.1 con extensiones)
  web:
    build: . # <--- CAMBIO AQUÍ. Construye la imagen desde el Dockerfile local
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    depends_on:
      - db

  # 2. SERVICIO DE BASE DE DATOS (MariaDB/MySQL)
  db:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: my_project_db
    volumes:
      - ./db-data:/var/lib/mysql
    restart: unless-stopped

  # 3. ADMINISTRADOR DE BASE DE DATOS (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped